const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Cnds.IsOnScreen,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Acts.SetBoolVar
	];
};
self.C3_JsPropNameTable = [
	{alti: 0},
	{bes: 0},
	{bir: 0},
	{dokuz: 0},
	{dort: 0},
	{iki: 0},
	{sekiz: 0},
	{sifir: 0},
	{uc: 0},
	{yedi: 0},
	{sil: 0},
	{c1: 0},
	{c2: 0},
	{c3: 0},
	{c4: 0},
	{k1: 0},
	{k2: 0},
	{k3: 0},
	{k4: 0},
	{m1: 0},
	{m2: 0},
	{m3: 0},
	{m4: 0},
	{p1: 0},
	{p2: 0},
	{p3: 0},
	{p4: 0},
	{btnBasla: 0},
	{btnBilgi: 0},
	{kapla: 0},
	{btnFullScreen: 0},
	{btnHazirlayanlar: 0},
	{btnHome: 0},
	{btnKaynakca: 0},
	{durum: 0},
	{btnMuzik: 0},
	{btnSes: 0},
	{btnTekrar: 0},
	{hesapla: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{gameBackground: 0},
	{home: 0},
	{cam: 0},
	{plastik: 0},
	{metal: 0},
	{kagit: 0},
	{camm: 0},
	{kagitt: 0},
	{plastikk: 0},
	{metall: 0},
	{Veri: 0},
	{background2: 0},
	{Sine: 0},
	{bilgi: 0},
	{kg: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{bilgisyf: 0},
	{carpi: 0},
	{hazirlayanlar: 0},
	{kaynakca: 0},
	{butonlar: 0},
	{anabuton: 0},
	{textler: 0},
	{camText: 0},
	{kagitText: 0},
	{plastikText: 0},
	{metalText: 0},
	{discizgi: 0},
	{verigirisi: 0}
];

self.InstanceType = {
	alti: class extends self.ISpriteInstance {},
	bes: class extends self.ISpriteInstance {},
	bir: class extends self.ISpriteInstance {},
	dokuz: class extends self.ISpriteInstance {},
	dort: class extends self.ISpriteInstance {},
	iki: class extends self.ISpriteInstance {},
	sekiz: class extends self.ISpriteInstance {},
	sifir: class extends self.ISpriteInstance {},
	uc: class extends self.ISpriteInstance {},
	yedi: class extends self.ISpriteInstance {},
	sil: class extends self.ISpriteInstance {},
	c1: class extends self.ITextInstance {},
	c2: class extends self.ITextInstance {},
	c3: class extends self.ITextInstance {},
	c4: class extends self.ITextInstance {},
	k1: class extends self.ITextInstance {},
	k2: class extends self.ITextInstance {},
	k3: class extends self.ITextInstance {},
	k4: class extends self.ITextInstance {},
	m1: class extends self.ITextInstance {},
	m2: class extends self.ITextInstance {},
	m3: class extends self.ITextInstance {},
	m4: class extends self.ITextInstance {},
	p1: class extends self.ITextInstance {},
	p2: class extends self.ITextInstance {},
	p3: class extends self.ITextInstance {},
	p4: class extends self.ITextInstance {},
	btnBasla: class extends self.ISpriteInstance {},
	btnBilgi: class extends self.ISpriteInstance {},
	btnFullScreen: class extends self.ISpriteInstance {},
	btnHazirlayanlar: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnKaynakca: class extends self.ISpriteInstance {},
	btnMuzik: class extends self.ISpriteInstance {},
	btnSes: class extends self.ISpriteInstance {},
	btnTekrar: class extends self.ISpriteInstance {},
	hesapla: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	gameBackground: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	plastik: class extends self.ISpriteInstance {},
	metal: class extends self.ISpriteInstance {},
	kagit: class extends self.ISpriteInstance {},
	camm: class extends self.ISpriteInstance {},
	kagitt: class extends self.ISpriteInstance {},
	plastikk: class extends self.ISpriteInstance {},
	metall: class extends self.ISpriteInstance {},
	Veri: class extends self.ITextInputInstance {},
	background2: class extends self.ISpriteInstance {},
	bilgi: class extends self.ISpriteInstance {},
	kg: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	bilgisyf: class extends self.ISpriteInstance {},
	carpi: class extends self.ISpriteInstance {},
	hazirlayanlar: class extends self.ISpriteInstance {},
	kaynakca: class extends self.ISpriteInstance {},
	butonlar: class extends self.ISpriteInstance {},
	anabuton: class extends self.ISpriteInstance {},
	textler: class extends self.ITextInstance {},
	camText: class extends self.ITextInstance {},
	kagitText: class extends self.ITextInstance {},
	plastikText: class extends self.ITextInstance {},
	metalText: class extends self.ITextInstance {},
	discizgi: class extends self.ISpriteInstance {}
}